"""Generate a reviewable pages sidecar from a site's tree/menu API (--sync-pages).

Normal pipeline runs NEVER call the tree API: they read config/<site>.pages.yaml,
which this module (re)generates on demand — so tree changes (additions, removals,
renames) arrive as a reviewable git diff before any harvest uses them, and runs
stay deterministic/offline. Inline `pages:` in the main config override sidecar
entries with the same id."""
import json

import yaml

from . import common, config_loader, fetch

GENERATED_HEADER = (
    "# GENERATED by `python run.py <config> --sync-pages` — do not hand-edit.\n"
    "# Regenerate when the site's doc tree changes, review the git diff, then run\n"
    "# the normal pipeline. Inline `pages:` in the main config override same-id\n"
    "# entries from this file.\n")


def _walk(nodes, spec, out):
    children_key = spec.get("children_pointer", "children")
    fields = spec.get("page_fields") or {"id": "id", "title": "title"}
    for node in nodes or []:
        if not isinstance(node, dict):
            continue
        children = node.get(children_key) or []
        if not children or not spec.get("leaf_only", True):
            page = {}
            for page_key, tree_field in fields.items():
                if node.get(tree_field) is not None:
                    page[page_key] = node[tree_field]
            if page:
                out.append(page)
        _walk(children, spec, out)


def sync(config_path):
    """Fetch the tree API named by `pages_from_tree` and write the sidecar.
    Returns (sidecar_path, page_count)."""
    with open(config_path, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    spec = cfg.get("pages_from_tree")
    if not spec:
        raise SystemExit(f"{config_path}: no `pages_from_tree` section — nothing to sync")

    headers = {k: fetch._env_sub(str(v)) for k, v in (spec.get("headers") or {}).items()}
    raw = common.fetch_url(fetch._quote_url(spec["url"]), headers=headers, timeout=60)
    data = json.loads(raw)
    roots = fetch._get_pointer(data, spec["root_pointer"]) if spec.get("root_pointer") else data

    pages = []
    _walk(roots if isinstance(roots, list) else [roots], spec, pages)

    # ids: prefer a stable tree field mapped via page_fields (ordinals shift when
    # the tree inserts a node — document that); zero-padded ordinal as fallback.
    width = max(2, len(str(len(pages))))
    non_api = {str(x) for x in spec.get("non_api_ids", [])}
    api_default = spec.get("api_default", True)
    for i, p in enumerate(pages, 1):
        p["id"] = str(p.get("id") or str(i).zfill(width))
        p.setdefault("title", p["id"])
        if "api" not in p:
            p["api"] = p["id"] not in non_api and api_default

    out_path = config_loader.sidecar_path(config_path)
    body = yaml.safe_dump({"pages": pages}, allow_unicode=True, sort_keys=False)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(GENERATED_HEADER + body)
    return out_path, len(pages)
